# Generated by Django 4.2.3 on 2023-09-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False, verbose_name='CI')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='COD_PRODUCTO')),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=12)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID_PROVEEDOR')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provee',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('cod_producto', models.ForeignKey(db_column='COD_PRODUCTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
                ('id_proveedor', models.ForeignKey(db_column='ID_PROVEEDOR', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('ci', models.ForeignKey(db_column='CI', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
                ('cod_producto_id', models.ForeignKey(db_column='COD_PRODUCTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
            ],
        ),
    ]
