# Generated by Django 4.2.3 on 2023-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False, verbose_name='CI')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
