# Generated by Django 4.2.3 on 2023-08-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='COD_PRODUCTO')),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=12)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
