# Generated by Django 4.2.3 on 2023-08-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
    ]
