# Generated by Django 4.2.3 on 2023-08-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provee',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'provee',
                'managed': False,
            },
        ),
    ]
